language: python
sudo: false
python: 2.7
services: mysql
env:
    global:
        - DB_HOST=localhost
        - DB_USER=travis
        - DB_PASSWORD=''
    matrix:
        - TOX_ENV=py27-django16
        - TOX_ENV=py27-django17
        - TOX_ENV=py27-django18
        - TOX_ENV=flake8
install:
    - pip install tox==1.8
before_script:
    - mysql -e 'create database name_test;'
script:
    - env
    - tox -e $TOX_ENV -- --capture=no
